dist: xenial
services:
  - xvfb
addons:
  chrome: stable
language: smalltalk
before_install:
  # FIX Chrome install error
  - sudo apt-get update
  - sudo apt-get install -y dpkg
  - sudo dpkg -i /tmp/google-chrome-stable_current_amd64.deb
before_script:
  - wget http://selenium-release.storage.googleapis.com/3.141/selenium-server-standalone-3.141.59.jar
  - wget https://chromedriver.storage.googleapis.com/78.0.3904.105/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - "java -Dwebdriver.chrome.driver=chromedriver -jar selenium-server-standalone-3.141.59.jar -port 4444 > /tmp/seleniumlog.&"
smalltalk:
  - Pharo64-8.0
  - Pharo-7.0
  
matrix:
  allow_failures:
    - smalltalk: Pharo64-8.0

